name: efood_multivendor
description: A new Flutter application.
publish_to: 'none' #
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  path_provider: ^2.0.2
  url_strategy: ^0.2.0
  pin_code_fields: ^7.2.0
  geolocator: ^7.1.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  flutter_google_places: ^0.3.0
  flutter_typeahead: ^3.1.3
  carousel_slider: ^4.0.0-nullsafety.0
  shimmer_animation: ^2.0.0
  image_picker: ^0.8.0+4
  universal_html: ^2.0.8
  universal_ui: ^0.0.8
  webview_flutter: ^2.0.9
  flutter_widget_from_html_core: ^0.6.1+3
  url_launcher: ^6.0.7
  http: ^0.13.3
  pointer_interceptor: ^0.9.0+1
  phone_number: ^0.11.0+2
  country_code_picker: ^2.0.2
  change_app_package_name: ^1.0.0
  full_screen_image: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900